### ISSUE TITLE
Week 2 Out of Class : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#1]
**IBM Hills Overview**
[https://ibm.co/2AfH2yA](https://ibm.co/2AfH2yA)

**Medium Post on Hills** 
[https://bit.ly/38iXP4h](https://bit.ly/38iXP4h)

**Comment by akallish** [comment]
@F2021MartinRon @gauribhatt @z-schwartz How is this exercise going. If it is started, then someone in uour team should go to the Kanban and move this item into "In Progress."

If there are any questions about it, put it in this issue and "@" the appropriate people to respond. 

Thanks. @akallish

**Comment by gauribhatt** [comment]
@z-schwartz @ronjmartin are we done with this? can we move it ahead?

**Comment by akallish** [comment]
@gauribhatt @z-schwartz @F2021MartinRon this is a good conversation. Communicate where each of you are at to align on moving to done.

**Comment by z-schwartz** [comment]
Thanks @akallish  -- @gauribhatt - will complete in time for our meeting on Monday.

**Comment by F2021MartinRon** [comment]
Just finished the readings. Wow, that definition of Hills from IBM really cleared things up for me, it will be interesting to see how we decompose the project we selected. @gauribhatt @z-schwartz

**Comment by akallish** [comment]
@F2021MartinRon i am glad the IBM article helpful to understand the hills concept. It is a powerful way to define purpose, value and then all the details

**Comment by z-schwartz** [comment]
Reviewed and ready for our meeting tonight @5 - moving to done
@gauribhatt @F2021MartinRon
