### ISSUE TITLE
Week 3 Out of Class Work : Create 20 user stories for your decomposed hill

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#10]
- take all sub-hill statements and cluster them into groups
- name each group as this is your "epic" or body of work
- then write 20 user stories to address the details of your epics
- open 20 separate story issues into your team GitHub repository. create "(epic name)" and "story" tags and associate them with specific stories so you can filter all stories by tag or multiple tags
- iterate on three stories and want to see three versions in GitHub issue
- in ZenHub, move all stories into the backlog pipeline

Team 2 : [https://bit.ly/2YbKJUw](https://bit.ly/2YbKJUw)

**Comment by z-schwartz** [comment]
4 stories each by Monday

- [x]  @F2021MartinRon 
- [x] @gauribhatt 
- [x] @Tosgirl 
- [x] @z-schwartz 
- [x] @UjjwalAS

**Comment by akallish** [comment]
@UjjwalAS @z-schwartz @ronjmartin @Tosgirl @gauribhatt 

I took a look at your working mural to connect sub-hills into epics into stories. Overall, good progress but there are areas to improve:

Epic Names

"Planning for the future" should maybe be called "Forecasting"
"Aligning Outcomes" should maybe should be called “Volunteer matching“
"Incentives through Gamification" should maybe should be called “Rewards”

Stories:

There should be about double the stories to address each sub-hill statement. The stories themselves can be sharpened as the "I want" and "So that" statements should the same. Remember, the "I want" is the enabling task and "so that" is the wow or benefit. 

REMEMBER in the 20 stories that go into GitHub as separate issues, Remember to put at the top of each issue :
• the project goal
• the requisite sub-hill statement
• the story

For five stories, I want to see three iterations of refining the story.
