### ISSUE TITLE
Week 3 Out of Class : Review Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#11]
- – - – - – - – - – - – - – - – - – - 
How to write user stories 
[http://bit.ly/2IMDQwJ](http://bit.ly/2IMDQwJ)
[http://bit.ly/2I1gZMM](http://bit.ly/2I1gZMM)

- – - – - – - – - – - – - – - – - – - 
GitHub Overviews 
[http://bit.ly/2Gedxhz](http://bit.ly/2Gedxhz)
[http://bit.ly/2G8muwR](http://bit.ly/2G8muwR)

**Comment by z-schwartz** [comment]
@F2021MartinRon @Tosgirl @gauribhatt @UjjwalAS 

Please prioritize "how to write user stories" as it will be critical for our agenda tomorrow.

**Comment by UjjwalAS** [comment]
@F2021MartinRon @Tosgirl @gauribhatt @z-schwartz I am done with the videos.

**Comment by z-schwartz** [comment]
Same. Complete.

**Comment by F2021MartinRon** [comment]
Done with videos!

**Comment by gauribhatt** [comment]
Done!
