### ISSUE TITLE
Week 3 Out of Class : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#12]
- – - – - – - – - – - – - – - – - – - 
What are user stories? 
[http://bit.ly/2Gmw7Y6](http://bit.ly/2rjMACX)
[http://bit.ly/2IQVdwl](http://bit.ly/2rjMACX) 
[http://bit.ly/2pDhEgx](http://bit.ly/2rjMACX)

- – - – - – - – - – - – - – - – - – - 
GitHub Functions

GitHub Issues 
[http://bit.ly/2rjMACX](http://bit.ly/2rjMACX)

Creating tasks in issues(http://bit.ly/2rjMACX) 
[http://bit.ly/2HSHGGG](http://bit.ly/2rjMACX)

Text Formatting 
[http://bit.ly/2YceDov](http://bit.ly/2rjMACX)

**Comment by z-schwartz** [comment]
@UjjwalAS @Tosgirl @ronjmartin @gauribhatt 

Please prioritize the "what are user stories" section for tomorrows 10am meeting.

**Comment by UjjwalAS** [comment]
@akallish all the links in this issue take us to the same article. I don't know if that is deliberate or there is some error. Please let us know likewise
@F2021MartinRon @gauribhatt @z-schwartz @Tosgirl done with the reading of this article .

**Comment by z-schwartz** [comment]
Same. Complete.

**Comment by F2021MartinRon** [comment]
Done as well!

**Comment by gauribhatt** [comment]
Done!
