### ISSUE TITLE
Week 3: Fill in Availability

### ISSUE THREAD

**Issue by z-schwartz** [IITIDIDX597/F2021_Team2#16]
@Tosgirl & @UjjwalAS 

- [ ] Fill in your availability [here](https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1630633546801/31d093c7061935ef6e223d249010be3adde8e4a3?sender=u25ae04772ab4ab1952657846)

**Comment by UjjwalAS** [comment]
@Zach , Availability has been filled from our end, we can decide the next meetings in tomorrow’s meeting
