### ISSUE TITLE
Week 2 Out of Class : Who are we as a team? Mural

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#3]
You have been assigned a team. Right now you are a group of individuals that is not interdependent yet.
 
So you need to come together and share key quantitative and qualitative information about each other. But these are facts and you need to discuss what they mean to each other.

This is the start to begin a rapport and to learn to trust each other because each of you have shared and unique experiences and talents that can help you understand your team’s talent density.

[Mural Board](https://bit.ly/3iIgjRI)

**Comment by akallish** [comment]
@F2021MartinRon @gauribhatt @z-schwartz How is this exercise going. If it is started, then someone in uour team should go to the Kanban and move this item into "In Progress."

If there are any questions about it, put it in this issue and "@" the appropriate people to respond. 

Thanks. @akallish

**Comment by gauribhatt** [comment]
First, two sections will be done asynchronously before our next meeting @ronjmartin @z-schwartz 
Third section will be filled in together during the next meeting

**Comment by akallish** [comment]
@gauribhatt time shifting to do tasks that are reviewed synchronously is an art that this class will master

**Comment by z-schwartz** [comment]
@gauribhatt @F2021MartinRon 
Done and ready for review.

**Comment by F2021MartinRon** [comment]
@gauribhatt @z-schwartz 
Also done and ready for review

**Comment by gauribhatt** [comment]
Done and ready for review, team!
