### ISSUE TITLE
Week 2 Out of Class : Complete goals, hills, definitions & sub-hills Mural

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#4]
This is a critical group exercise and cannot be done asynchronously. Be prepared to invest two to three hours of time, in one or two synchronous sessions.

[Mural Board](https://bit.ly/3y6B5yM)

**Comment by akallish** [comment]
@F2021MartinRon @gauribhatt @z-schwartz If it is started, then someone in your team should go to the Kanban and move this item into "In Progress."

If there are any questions about it, put it in this issue and "@" the appropriate people to respond. 

Thanks. @akallish

**Comment by F2021MartinRon** [comment]
Meet again to present projects and decide during the meeting @z-schwartz  @gauribhatt

**Comment by akallish** [comment]
@gauribhatt @z-schwartz @F2021MartinRon Good Morning. I would get started on your hills exercise as soon as possible
