### ISSUE TITLE
Week 4 : 3 Questions by each student due on Friday, September 10

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#45]
Each student will submit three questions to Adam in this GitHub issue. 

Questions should be about what you are learning in Agile Culture and its applicability in professional design practice. No questions about jobs.   Questions are due in this GitHub issue by September 10.

Adam will collate all questions into themes and send them to  Evan for review.

**Comment by akallish** [comment]
@F2021MartinRon @gauribhatt @UjjwalAS @Tosgirl @z-schwartz Remember to post your three questions by end of day today.

**Comment by z-schwartz** [comment]
- Do you segment design activity and agile activity? Or have you found ways to blend aspects of design into agile culture/methodology? vice versa? 

- Was Agile a part of the work culture? Or did you have to socialize and sell the the process? If you were to give a 30 second elevator pitch, what would it sound like? 

- How have you evolved Agile methodology to fit your specific teams needs? 

- Can you share how your approach to Agile has evolved since Adam's and into your professional career? 

- given how central human centered design is to our practice; in what ways have you had to adjust agile processes in order to support the humans in the process of agile? Is there a rule of thumb that helps you determine whether to keep firm on process or to adjust?

**Comment by F2021MartinRon** [comment]
1. How have elements of agile culture impacted your working relationships with non-designer roles, e.g. engineers, developers, civic sector professionals, etc.? Any particularly difficult hurdles you have had to clear for this?

2. What aspects of Agile culture have you found easier or harder to implement in your past role? 

3. Can you give an example of how your organization or team practices the agile principle that "the work should always be visible to all"?

**Comment by akallish** [comment]
@z-schwartz @F2021MartinRon thank you for your question submissions.

**Comment by gauribhatt** [comment]
1. What has your experience been like trying to apply classroom learnings of agile at work? Could you share a story where you have applied agile to a real-world project?

2. What are the different workspaces (digital/physical) that you engage with on a regular basis at work? How does working with multiple workspaces foster an agile environment?

3. What, according to you/in your work experience, is the relationship between human centred design and agile? How do they balance each other? and what are the distinct differences?

**Comment by akallish** [comment]
@gauribhatt Thank you for submitting your questions

**Comment by UjjwalAS** [comment]
1. What are agile method's distinct and quantifiable advantages over conventional HCD practice (it would be great if you could tell us incidents)? and what are a few of its limitations that you would want us to be aware of and improvise? 

2. This method may seem very intimidating to individuals who haven’t experienced it before, like myself where it felt really intimidating in the beginning but them I became comfortable with the tools and process once I got into it. Have you ever come across incidents where you had to convince people/ teams or management to adopt this method and how did you convince them?  

3. In the industry and real practice does agile improve the quality of outcomes? Reduce lead times and increase productivity? Encourage accountability? benefits from synchronous and asynchronous collaboration? keep team members happy and satisfied?

4. How do you see agile method’s adoption into organizations that are working to develop hardware products, where the lead times are much higher and there are more interdependencies and verticals (out of the core team) involved?  

Context: For example a core software team may include project managers, designers ( researchers, UX, UI, animation etc.), developers (front end and back end), marketing and business (product team, branding, SMM etc.) Whereas a hardware company may include designers, design engineers, marketing team, rapid prototyping teams, vendors, manufacturing partners (in house and overseas, QC team, packaging team etc. I personally see agile working very efficiently for software / digital products but not the same for hardware products, although hardware organizations are practicing it too.

5. In the class, I have personally felt this method's effectiveness, specially when it comes to decomposing a goal into fine granularity that makes assumptions and ideas clearer. But here we are solving a "not so complex" problem. What are your views of this method's effectiveness on complex, system level problems?

**Comment by akallish** [comment]
@UjjwalAS thank you for your questions

**Comment by Tosgirl** [comment]
1.  I feel agile methods (decomposition / working synchronously / asynchronously) are time consuming and draggy, though the are effective. How do organizations with few number of staff plan, design and implement multiple projects to give the best result within a given time using these methods?

2. Will agile be relevant in the future of design and how applicable is agile in healthcare (like practical administration/treatment of a patient in the hospital where every one is busy and their goal is to get the work done)?

3. How many agile tools from this class are you currently using? Kindly describe the effect of agile culture in the organizationally culture? 

4. Is agile absolutely a result of technological advancement, company expansion or user demand?

**Comment by akallish** [comment]
@Tosgirl Thank you for submitting your questions.

**Comment by akallish** [comment]
@UjjwalAS Thank you for submitting your questions and the additional comments.
