### ISSUE TITLE
Week 7 : Schedule mandatory 60 minute dry run of team presentation the week of September 29

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#46]
[Link to overview](https://drive.google.com/file/d/1ajcsnQmfD68oxdQzcOmmoKnkC7ZtJZgd/view?usp=sharing)

Send @akallish a few times and dates to choose from.

**Comment by z-schwartz** [comment]
@gauribhatt @UjjwalAS @Tosgirl 

Referencing the sandbox, it appears the three dates below from 5-6 (however, classes wrap up at 5 and start at 6 whomever has a class so might be tight) are optimal. I cannot commit to that Friday. Team? 

Monday the 27th
Tuesday the 28th
Wednesday the 29th

**Comment by gauribhatt** [comment]
All these 3 dates work for me.

**Comment by ronjmartin** [comment]
Any of those three dates work for me as well

**Comment by UjjwalAS** [comment]
@ronjmartin @gauribhatt @z-schwartz @Tosgirl 
for me 
Monday - 12:00 PM- 2:00 PM and after 5:00 PM works 
Tuesday - 9:00AM - 12:00 PM and 2:00 PM - 6:00 PM works
Wednesday - 9:00 AM - 12:00 PM and 2:00 PM-6:00 PM works

Also wanted to confirm if we are meeting any day over the weekend, like last week

**Comment by z-schwartz** [comment]
@ronjmartin @gauribhatt @z-schwartz @Tosgirl @akallish 
Let's proceed with 6pm on Wednesday the 29th for our dry run.

**Comment by UjjwalAS** [comment]
@F2021MartinRon @gauribhatt @Tosgirl  @z-schwartz 
This works for me

**Comment by akallish** [comment]
This will be good

**Comment by Tosgirl** [comment]
Monday and Wednesday works for me.

**Comment by akallish** [comment]
We cannot do Wednesday the 29th as we have class that evening. So it may need to be Tuesday the 28th

**Comment by akallish** [comment]
We will do Monday, September 27 at 06:00pm
