### ISSUE TITLE
Week 5 Out of Class Work : Watch Online Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#50]
Review these videos BEFORE branching and writing acceptance criteria

Story to Acceptance Criteria
[http://bit.ly/2E7JqGq](http://bit.ly/2E7JqGq)

**Comment by UjjwalAS** [comment]
@F2021MartinRon @gauribhatt @Tosgirl @z-schwartz 
done with this

**Comment by UjjwalAS** [comment]
@F2021MartinRon  @gauribhatt  @Tosgirl  @z-schwartz 
Once everyone is done I can move this to done

**Comment by z-schwartz** [comment]
> @F2021MartinRon @gauribhatt @Tosgirl @z-schwartz
> done with this

same. done.

**Comment by gauribhatt** [comment]
done

**Comment by Tosgirl** [comment]
Done with this too
