### ISSUE TITLE
Week 5 Out of Class Work : Create acceptance criteria for your five selected stories

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team2#51]
- Three iterations of acceptance criteria for each story is required.
- Use the same selected story issue and iterate on acceptance criteria that is testable to secure that particular story

**Comment by z-schwartz** [comment]
Each person select 1 issue to develop acceptance criteria for

Each person iterate on another issue that is not yours 

See issue for assignments

**Comment by Tosgirl** [comment]
All done
