### ISSUE TITLE
Review Key Points in Community Catalyst Miro Board

### ISSUE THREAD

**Issue by z-schwartz** [IITIDIDX597/F2021_Team2#6]
Team, here is the [Miro Link](https://miro.com/app/board/o9J_lXleEzM=/) for the community catalyst project.

If you're curious, feel free to poke about. Otherwise, we'll share 5-10 minutes in our meeting tomorrow to review key details that will help contextualize/enrichen our understanding of the concept space.

**Comment by akallish** [comment]
@z-schwartz what is this about? Is there a link to a Miro board?

**Comment by z-schwartz** [comment]
Hi @akallish working on it now - was a filler until I pull the details together.  Will update.
