### ISSUE TITLE
Define 3 assigned terms 

### ISSUE THREAD

**Issue by z-schwartz** [IITIDIDX597/F2021_Team2#7]

**Comment by z-schwartz** [comment]
**Assigned terms**
Please have these done as soon as you are able. Once completed, _attempt_ 1 sub hill - we'll use as a jumping off point in our team meeting. 

@gauribhatt [volunteer, a way to see, growth]
@F2021MartinRon [overtime, dashboard, taking control
@z-schwartz [personal, vocational, communal]

**Comment by akallish** [comment]
There should be about 10 or 15 sub-hills that can easily be generated from one hill and definitions. Tracking them to specific definitions and parts of the hill is the challenge.

**Comment by gauribhatt** [comment]
Done!

**Comment by akallish** [comment]
That is music to my ears

**Comment by gauribhatt** [comment]
> That is music to my ears

Oh no, my response was for @z-schwartz! We will however, try to attempt as many sub-hills as we can

**Comment by z-schwartz** [comment]
@gauribhatt @F2021MartinRon: 3 assigned terms defined.
